var annotated_dup =
[
    [ "COFFI", "namespace_c_o_f_f_i.html", [
      [ "architecture_provider", "class_c_o_f_f_i_1_1architecture__provider.html", "class_c_o_f_f_i_1_1architecture__provider" ],
      [ "auxiliary_symbol_record", "struct_c_o_f_f_i_1_1auxiliary__symbol__record.html", null ],
      [ "auxiliary_symbol_record_1", "struct_c_o_f_f_i_1_1auxiliary__symbol__record__1.html", null ],
      [ "auxiliary_symbol_record_2", "struct_c_o_f_f_i_1_1auxiliary__symbol__record__2.html", null ],
      [ "auxiliary_symbol_record_3", "struct_c_o_f_f_i_1_1auxiliary__symbol__record__3.html", null ],
      [ "auxiliary_symbol_record_4", "struct_c_o_f_f_i_1_1auxiliary__symbol__record__4.html", null ],
      [ "auxiliary_symbol_record_5", "struct_c_o_f_f_i_1_1auxiliary__symbol__record__5.html", null ],
      [ "coff_file_header", "struct_c_o_f_f_i_1_1coff__file__header.html", "struct_c_o_f_f_i_1_1coff__file__header" ],
      [ "coff_file_header_ti", "struct_c_o_f_f_i_1_1coff__file__header__ti.html", "struct_c_o_f_f_i_1_1coff__file__header__ti" ],
      [ "coff_header", "class_c_o_f_f_i_1_1coff__header.html", null ],
      [ "coff_header_impl", "class_c_o_f_f_i_1_1coff__header__impl.html", null ],
      [ "coff_header_impl_ti", "class_c_o_f_f_i_1_1coff__header__impl__ti.html", null ],
      [ "coff_header_impl_tmpl", "class_c_o_f_f_i_1_1coff__header__impl__tmpl.html", null ],
      [ "coff_optional_header_pe", "struct_c_o_f_f_i_1_1coff__optional__header__pe.html", "struct_c_o_f_f_i_1_1coff__optional__header__pe" ],
      [ "coff_optional_header_pe_plus", "struct_c_o_f_f_i_1_1coff__optional__header__pe__plus.html", "struct_c_o_f_f_i_1_1coff__optional__header__pe__plus" ],
      [ "coffi", "class_c_o_f_f_i_1_1coffi.html", "class_c_o_f_f_i_1_1coffi" ],
      [ "coffi_strings", "class_c_o_f_f_i_1_1coffi__strings.html", "class_c_o_f_f_i_1_1coffi__strings" ],
      [ "coffi_symbols", "class_c_o_f_f_i_1_1coffi__symbols.html", "class_c_o_f_f_i_1_1coffi__symbols" ],
      [ "common_optional_header_ti", "struct_c_o_f_f_i_1_1common__optional__header__ti.html", "struct_c_o_f_f_i_1_1common__optional__header__ti" ],
      [ "directories", "class_c_o_f_f_i_1_1directories.html", "class_c_o_f_f_i_1_1directories" ],
      [ "directory", "class_c_o_f_f_i_1_1directory.html", "class_c_o_f_f_i_1_1directory" ],
      [ "dos_header", "class_c_o_f_f_i_1_1dos__header.html", null ],
      [ "image_data_directory", "struct_c_o_f_f_i_1_1image__data__directory.html", null ],
      [ "line_number", "struct_c_o_f_f_i_1_1line__number.html", "struct_c_o_f_f_i_1_1line__number" ],
      [ "msdos_header", "struct_c_o_f_f_i_1_1msdos__header.html", "struct_c_o_f_f_i_1_1msdos__header" ],
      [ "msdos_header_rel", "struct_c_o_f_f_i_1_1msdos__header__rel.html", null ],
      [ "optional_header", "class_c_o_f_f_i_1_1optional__header.html", null ],
      [ "optional_header_impl_pe", "class_c_o_f_f_i_1_1optional__header__impl__pe.html", null ],
      [ "optional_header_impl_pe_plus", "class_c_o_f_f_i_1_1optional__header__impl__pe__plus.html", null ],
      [ "optional_header_impl_ti", "class_c_o_f_f_i_1_1optional__header__impl__ti.html", null ],
      [ "optional_header_impl_tmpl", "class_c_o_f_f_i_1_1optional__header__impl__tmpl.html", null ],
      [ "rel_entry", "struct_c_o_f_f_i_1_1rel__entry.html", null ],
      [ "rel_entry_ceva", "struct_c_o_f_f_i_1_1rel__entry__ceva.html", null ],
      [ "rel_entry_generic", "struct_c_o_f_f_i_1_1rel__entry__generic.html", null ],
      [ "rel_entry_ti", "struct_c_o_f_f_i_1_1rel__entry__ti.html", null ],
      [ "relocation", "class_c_o_f_f_i_1_1relocation.html", null ],
      [ "section", "class_c_o_f_f_i_1_1section.html", null ],
      [ "section_header", "struct_c_o_f_f_i_1_1section__header.html", null ],
      [ "section_header_ti", "struct_c_o_f_f_i_1_1section__header__ti.html", null ],
      [ "section_impl", "class_c_o_f_f_i_1_1section__impl.html", null ],
      [ "section_impl_ti", "class_c_o_f_f_i_1_1section__impl__ti.html", null ],
      [ "section_impl_tmpl", "class_c_o_f_f_i_1_1section__impl__tmpl.html", "class_c_o_f_f_i_1_1section__impl__tmpl" ],
      [ "sections", "class_c_o_f_f_i_1_1sections.html", "class_c_o_f_f_i_1_1sections" ],
      [ "sections_provider", "class_c_o_f_f_i_1_1sections__provider.html", "class_c_o_f_f_i_1_1sections__provider" ],
      [ "string_to_name_provider", "class_c_o_f_f_i_1_1string__to__name__provider.html", "class_c_o_f_f_i_1_1string__to__name__provider" ],
      [ "symbol", "class_c_o_f_f_i_1_1symbol.html", null ],
      [ "symbol_provider", "class_c_o_f_f_i_1_1symbol__provider.html", "class_c_o_f_f_i_1_1symbol__provider" ],
      [ "symbol_record", "struct_c_o_f_f_i_1_1symbol__record.html", null ],
      [ "win_header", "class_c_o_f_f_i_1_1win__header.html", null ],
      [ "win_header_impl", "class_c_o_f_f_i_1_1win__header__impl.html", null ],
      [ "win_header_pe", "struct_c_o_f_f_i_1_1win__header__pe.html", null ],
      [ "win_header_pe_plus", "struct_c_o_f_f_i_1_1win__header__pe__plus.html", null ]
    ] ]
];